### ISSUE TITLE
No operator% for arithmetic types

### ISSUE THREAD

**Issue by yog-muskrat** [rollbear/strong_type#11]
Hi!
Description of `strong::arithmetic` modifier says:  
```
strong::arithmetic allows addition, subtraction, multiplication, division and **remainder** of instances.
```
But there is no `operator%` for this modifier. Is there any reason not to have it?

**Comment by rollbear** [comment]
Oh... I think my brain must've blanked. I'll add it later today. Thanks.

**Comment by rollbear** [comment]
It's fixed on `main` now.. It was a little bit tricky because the operation doesn't make sense for all underlying types, e.g. floating point types, so I made the operator conditionally supported.

I'll leave this issue open until a release has been tagged with the fix.

**Comment by yog-muskrat** [comment]
Great!
Thank you, Björn!

**Comment by rollbear** [comment]
Just tagged v4 which includes this fix. Closing now.
