### ISSUE TITLE
Overriding std::is_arithmetic<> for program-defined type is undefined behaviour?

### ISSUE THREAD

**Issue by saxbophone** [rollbear/strong_type#19]
In the README, it's specified:

> For modifier strong::arithmetic, the type trait std::is_arithmetic<> is true.

According to the standard, this is undefined behaviour:

> - None of the templates defined in [<type_traits>](https://en.cppreference.com/w/cpp/header/type_traits) may be specialized for a program-defined type, except for [std::common_type](https://en.cppreference.com/w/cpp/types/common_type) and [std::basic_common_reference](https://en.cppreference.com/w/cpp/types/common_reference#Helper_types) (since C++20). This includes the [type traits](https://en.cppreference.com/w/cpp/types) and the class template [std::integral_constant](https://en.cppreference.com/w/cpp/types/integral_constant).
>
> [(source — cppreference.com)](https://en.cppreference.com/w/cpp/language/extending_std#:~:text=None%20of%20the%20templates%20defined%20in%20%3Ctype_traits%3E%20may%20be%20specialized%20for%20a%20program%2Ddefined%20type%2C%20except%20for%20std%3A%3Acommon_type%20and%20std%3A%3Abasic_common_reference%20(since%20C%2B%2B20).%20This%20includes%20the%20type%20traits%20and%20the%20class%20template%20std%3A%3Aintegral_constant.)

Maybe `std::numeric_limits<>` should be specialised instead, to provide type-traits? That one is open to extension, _provided_ one doesn't reopen the `std` namespace and just specialises the fully-qualified name of the template...

**Comment by rollbear** [comment]
Right. Bummer. I should've known this. Dropping it is also a potentially breaking change for some users, but it's the way to go. Thanks for reporting.

**Comment by timblechmann** [comment]
related to specializing `std::is_arithmetic`, this code gives me a compile error with catch2 v3

```
TEST_CASE( "testme", "" )
{
    using test_type
        = strong::type< std::int8_t, struct tag, strong::arithmetic, strong::default_constructible, strong::equality >;

    constexpr test_type a;
    test_type           b;
    CHECK( a == b );
}
```

```
my/test.cpp: error: use of overloaded operator '<=' is ambiguous (with operand types 'Catch::Decomposer' and 'const test_type' (aka 'const type<signed char, tag, strong::arithmetic, strong::default_constructible, strong::equality>'))
    catchAssertionHandler.handleExpr( Catch::Decomposer() <= a == b );
                                      ~~~~~~~~~~~~~~~~~~~ ^  ~
/path/to/catch2-v3/src/catch2/../catch2/internal/catch_decomposer.hpp:247:21: note: candidate function [with T = const strong::type<signed char, tag, strong::arithmetic, strong::default_constructible, strong::equality> &, $1 = 0]
        friend auto operator <= ( Decomposer &&, T && lhs ) -> ExprLhs<T const&> {
                    ^
/path/to/catch2-v3/src/catch2/../catch2/internal/catch_decomposer.hpp:252:21: note: candidate function [with T = strong::type<signed char, tag, strong::arithmetic, strong::default_constructible, strong::equality>, $1 = 0]
        friend auto operator <= ( Decomposer &&, T value ) -> ExprLhs<T> {
                    ^
1 error generated.
```

**Comment by rollbear** [comment]
Thanks @timblechmann , that was a very unexpected result of this. I'll get to fixing it as soon as I'm out of meetings.

**Comment by rollbear** [comment]
Fixed on main now. Leaving this open until a release is tagged.

**Comment by saxbophone** [comment]
Hurrah! How do you feel about going down the route of specializing `std::numeric_limits<>` instead?
IIRC, there are members within that struct that can provide similar traits-like functionality as you were providing with `is_arithmetic`, though I forget the names of the exact members.
I've got a previous specialisation of that struct I did for a personal project, maybe I'll dig that out (there's loads of definitions ☹️) and have a go hacking on strong_type...

**Comment by rollbear** [comment]
@saxbophone feel free to open a separate issue about that.

**Comment by rollbear** [comment]
Fix included in release v5

**Comment by saxbophone** [comment]
> @saxbophone feel free to open a separate issue about that.

Thanks, I think I will and I will also try and send a PR with the structure of the type traits stuff I mentioned.
