### ISSUE TITLE
Missing include for `fmt::ostream_formatter`

### ISSUE THREAD

**Issue by kiwixz** [rollbear/strong_type#27]
Hello, if fmt is present (the macro `FMT_VERSION` is defined), strong_type will require a manual include of `fmt/ostream.h` to get the `fmt::ostream_formatter` needed line 1687 in the header.

I think it should include it on its own, or maybe do some fancy magic to not error out when its absent.

I'm using strong_type v6 and fmt 9.1.0.

**Comment by rollbear** [comment]
I've made some changes regarding `{fmt}` after that release. Can you try main and tell me if there's more work to do?

**Comment by kiwixz** [comment]
It's fixed in main indeed (7b859d29f60c56f0fbfd173b2501c0e91721f9e0), thanks!
