### ISSUE TITLE
[v7] compilation failed via FetchContent

### ISSUE THREAD

**Issue by ksergey** [rollbear/strong_type#28]
Hi!

Try to include `strong_type` to my project via `FetchContent`:
```cmake
FetchContent_Declare(strong_type URL https://github.com/rollbear/strong_type/archive/refs/tags/v7.tar.gz)
FetchContent_MakeAvailable(strong_type)
```

But compilation failed on cmake project generation step:
```
-- Configuring done
CMake Error at build/_deps/strong_type-src/CMakeLists.txt:99 (add_executable):
  Target "self_test" links to target "Catch2::Catch2" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
```

Also will be good to explicit disable tests building

**Comment by rollbear** [comment]
Yeah, I need to fix this. Thanks. Until then, it's just one header file - there is nothing to build other than the tests.

**Comment by rollbear** [comment]
Can you check the branch [cmake_fixes](https://github.com/rollbear/strong_type/tree/cmake_fixes) to see if it works? There's an explicit option to CMake, `-DSTRONG_TYPE_UNIT_TEST=yes` to enable building the tests.

**Comment by ksergey** [comment]
This works for me!

```cmake
FetchContent_Declare(strong_type
  GIT_REPOSITORY https://github.com/rollbear/strong_type.git
  GIT_TAG cmake_fixes)
FetchContent_MakeAvailable(strong_type)
```

Thanks

**Comment by rollbear** [comment]
OK. Merged to main. I will leave this open until the fix is included in a tagged release.  Thanks for reporting.

**Comment by rollbear** [comment]
I just tagged a release v8, so closing this now.
