### ISSUE TITLE
Specialise std::numeric_limits<strong::type> for type traits

### ISSUE THREAD

**Issue by saxbophone** [rollbear/strong_type#29]
Related to #19 

strong_type used to override `std::is_arithmetic` for type traits, but this is not standards-compliant and was removed in v5.

`std::numeric_limits<>` is one of the few definitions in std that is permitted to be extended, as long as it's done in a certain way (i.e. without re-opening `namespace std`, using template specialisations only).

I said I could have a go at doing this and I think I will, I already have code I can reuse from another project where I overrode this, and loads of the definitions for numeric_limits (a huuge structure) are boilerplates...

**Comment by saxbophone** [comment]
@rollbear any further info on what type traits from numeric limits should be asserted for `strong::type` and friends welcome. I believe `strong::type` should assert "is arithmetic", as a starter..?

**Comment by rollbear** [comment]
That is a very interesting question. I'm a bit uncertain of what you mean with "...should be asserted for `strong::type`".

I guess which strong types have specialisations for numeric limits  must depend on the modifiers used, and reflect the capabilities of the underlying type and which operations are allowed. This could be tricky for some cases. E.g., does it make sense to have `min`, `lowest` and `max` for types that are not ordered?

**Comment by saxbophone** [comment]
*That is a very interesting question. I'm a bit uncertain of what you mean
with "...should be asserted for strong::type".*

I mean that (if my memory serves correct) previously this library provided
a specialisation for std::is_arithmetic<strong::type> and that presumably a
new type traits override that uses numeric limits (as allowed by the
standard) should provide the equivalent override.

**Comment by saxbophone** [comment]
Oh, I realise the confusion: I think I  meant to say strong:: arithmetic,
not strong::type

**Comment by rollbear** [comment]
Do you think something like this would be OK? I haven't tested it that much, but I believe it's alright. Maybe better to limit the specialization using `requires` when compiled with C++20.

https://godbolt.org/z/TqbcW9vc8

**Comment by saxbophone** [comment]
Cool, although IIRC, it's not allowed by the standard to extend
numeric_limits by opening up namespace std, I'm pretty sure the way I read
up how to do it was to use the full name std::numeric_limits<type> when
extending it. I believe I did this to provide numeric_limits type traits in
github.com/saxbophone/unmoving

**Comment by saxbophone** [comment]
Apologies, I linked the wrong repo, I meant to link this file, from this
line onwards:

https://github.com/saxbophone/arby/blob/master/arby/include/arby/Nat.hpp#L974

**Comment by rollbear** [comment]
I'll have a look. Thanks.

**Comment by saxbophone** [comment]
No problem —the example I have linked, specialises `numeric_limits<>` for a custom-built type of my own, which implements arbitrary-precision unsigned arithmetic. I've provided definitions for all of those specified by `numeric_limits`, even those which don't apply to my type (such as the floating-point ones). It's probably a reasonable basis to start modifying from...

**Comment by rollbear** [comment]
I admit it was a gamble with `std::numeric_limits<void>`, but it makes sense that the base template only has `is_specialized = false;`, which seems to be the case, at least in the big 3 libraries.

I think I got this now and will implement it as such. I need to make a few other changes first, though, to ensure that the constexpr predicate testing for `arithmetic` works for all modifiers. There are a few that are a bit uncooperative right now.

**Comment by saxbophone** [comment]
This is very cool, thanks!

**Comment by rollbear** [comment]
It's now on branch [numeric_limits](https://github.com/rollbear/strong_type/tree/numeric_limits) if you want to check it out.

**Comment by rollbear** [comment]
Included in tagged release v9, so closing now. Thank you.

**Comment by saxbophone** [comment]
That's great, thanks for putting this in! :)
