### ISSUE TITLE
Problem with 'optional' modifier example

### ISSUE THREAD

**Issue by usefulcat** [rollbear/strong_type#34]
I have a use case for which the optional modifier (described in 'Writing a modifier') seems perfectly suited. Unfortunately, I get redefinition errors for operator*() if I use this modifier in more than one strong type. In my case I don't need operator*() so I'll just do without it, but I thought you might want to update the documentation to either fix or describe this limitation. I would suggest something other than removing operator*(), but I'm afraid this problem is a bit beyond my knowledge of the language.

Below is an example to reproduce the problem. The code for optional was copied directly from the docs. I'm using gcc12 and clang14 with -std=c++20.

BTW thanks for this library, I appreciate it. I've been using NamedType for a while but thought I would give this a try when I realized optional might be able to replace some stuff that I've been doing in a more manual way.

```
#include <strong_type/strong_type.hpp>
#include <optional> // std::bad_optional_access

template <auto no_value>
struct optional
{
    template <typename T>
    struct modifier
    {
        constexpr bool has_value() const noexcept
        {
            auto& self = static_cast<const T&>(*this);
            return value_of(self) != no_value;
        }
        template <typename TT>
        friend constexpr decltype(auto) operator*(TT&& self) noexcept
        {
            return value_of(std::forward<TT>(self));
        }
        constexpr decltype(auto) value() &
        {
            return get_value(static_cast<T&>(*this));
        }
        constexpr decltype(auto) value() const &
        {
            return get_value(static_cast<const T&>(*this));
        }
        constexpr decltype(auto) value() &&
        {
            return get_value(static_cast<T&&>(*this));
        }
        constexpr decltype(auto) value() const &&
        {
            return get_value(static_cast<const T&&>(*this));
        }
    private:
        template <typename TT>
        static constexpr decltype(auto) get_value(TT&& t)
        {
            if (!t.has_value()) {
                throw std::bad_optional_access();
            }
            return value_of(std::forward<TT>(t));
        }
    };
};

// Note: no errors if you remove optional from either (or both) of these types.
// But it's not possible to use optional in both of them.
using Type1 =
    strong::type<
        int, struct Type1Tag,
        strong::regular
        ,optional<int(-1)>
        >;

using Type2 =
    strong::type<
        int, struct Type2Tag,
        strong::regular
        ,optional<int(-1)>
        >;

int main(int argc, char* argv[])
{
    [[maybe_unused]] const Type1 t1(1);
    [[maybe_unused]] const Type2 t2(2);
    return 0;
}

```

**Comment by rollbear** [comment]
Oops! My bad. Yes, the template friend is redefined. You need to explicitly write all 4 overloads of `operator*`. See https://godbolt.org/z/nPvfGKEjM. I'll update the README later today.

**Comment by rollbear** [comment]
It took a little longer than intended, but the README is updated now.

**Comment by usefulcat** [comment]
Awesome, thanks I will try that out tomorrow :)
