### ISSUE TITLE
``invocable`` mixin

### ISSUE THREAD

**Issue by DNKpp** [rollbear/strong_type#38]
Hey,
I've recently started using your library and I love the simplicity and extensibility. But I wonder why no ``invocable`` mixin exists, as this is probably something one could use a lot. I wrote one for myself, which may be a good baseline (it's mainly tedious repetition).

Any comments?
```cpp
struct invocable
{
	template <typename Strong>
	struct modifier
	{
		template <class... Args>
			requires std::invocable<const strong::underlying_type_t<Strong>&, Args...>
		constexpr decltype(auto) operator ()(
			Args&&... args
		) const & noexcept(std::is_nothrow_invocable_v<const strong::underlying_type_t<Strong>&, Args...>)
		{
			return std::invoke(as_underlying(), std::forward<Args>(args)...);
		}

		template <class... Args>
			requires std::invocable<strong::underlying_type_t<Strong>&, Args...>
		constexpr decltype(auto) operator ()(
			Args&&... args
		) & noexcept(std::is_nothrow_invocable_v<strong::underlying_type_t<Strong>&, Args...>)
		{
			return std::invoke(as_underlying(), std::forward<Args>(args)...);
		}

		template <class... Args>
			requires std::invocable<const strong::underlying_type_t<Strong>&&, Args...>
		constexpr decltype(auto) operator ()(
			Args&&... args
		) const && noexcept(std::is_nothrow_invocable_v<const strong::underlying_type_t<Strong>&&, Args...>)
		{
			return std::invoke(std::move(as_underlying()), std::forward<Args>(args)...);
		}

		template <class... Args>
			requires std::invocable<strong::underlying_type_t<Strong>&&, Args...>
		constexpr decltype(auto) operator ()(
			Args&&... args
		) && noexcept(std::is_nothrow_invocable_v<strong::underlying_type_t<Strong>&&, Args...>)
		{
			return std::invoke(std::move(as_underlying()), std::forward<Args>(args)...);
		}

	private:
		[[nodiscard]]
		constexpr const strong::underlying_type_t<Strong>& as_underlying() const noexcept
		{
			return value_of(static_cast<const Strong&>(*this));
		}

		[[nodiscard]]
		constexpr strong::underlying_type_t<Strong>& as_underlying() noexcept
		{
			return value_of(static_cast<Strong&>(*this));
		}
	};
};
```

**Comment by rollbear** [comment]
It's not there because I haven't thought of it, and no one has expressed an interest in it, until now. I can see why you'd want to be able to differentiate callback types with the same signatures, so I think this would be a good addition. This would be so much shorter in C++23 with explicit object parameter ("deducing this"), but we're not there yet.

If you'd like to submit a PR (with docs please) that'd be awesome. Unfortunately I have to ask you to back-port to C++14 if you do, so SFINAE constraints instead of `requires`, and no `std::invocable` and friends either.

I'm out traveling the rest of the week, so I may not be quick to respond.

**Comment by rollbear** [comment]
Back from traveling. I'll try to get this done today. Thanks for the suggestion.

**Comment by rollbear** [comment]
There, have a look at branch [invocable](https://github.com/rollbear/strong_type/tree/invocable) and tell me if it does what you think it should.

**Comment by DNKpp** [comment]
Hey, thank you for your work. I had a very busy week, so didn't find much time for this issue. Your implementation does fine and complies to my personal unit-tests. Thank you!
I wonder how the additional template args ``Tag`` and ``Ms`` are working. I used your example ``optional`` implementation as a reference, where they do not appear. Do you supply them conditionally?

**Comment by rollbear** [comment]
It's not necessary to use `type<T, Tag, Ms...>` as I did, it just gives direct access to `T` as the underlying type. `Tag` and `Ms...` are of no use in the template, but have to be spelled out when specializing the template this way.
