### ISSUE TITLE
strong::range , begin() and end() should be constexpr 

### ISSUE THREAD

**Issue by a4z** [rollbear/strong_type#41]
Thank you for this excellent library! 

I noticed that for strong::range , begin() and end() are not `constexpr` 

https://godbolt.org/z/Ghhj41db7

Could this be added?

**Comment by rollbear** [comment]
It probably can. I'll look into this in the next few days. Thanks for proposing it.

**Comment by rollbear** [comment]
Have a look at branch [constexpr_begin_end](https://github.com/rollbear/strong_type/tree/constexpr_begin_end) and let me know if it works for you. It also adds the .size() member function.

**Comment by a4z** [comment]
yes! awesome!! that fixes both,  this one, #41,  and #42 
Thank you!!

**Comment by rollbear** [comment]
Just tagged v14 which includes this. Closing now.
