### ISSUE TITLE
Feature request: extending strong::range with an additional option to get the size() property of a container

### ISSUE THREAD

**Issue by a4z** [rollbear/strong_type#42]
Mostly all of my usages of strong::range wrap a container, and often, latest at testing, I need to access the `size()` property.

Today I have to use `value_of(t).size()`. That works, but it would be extremely nice not to have to do that

In fact, wrapping containers is so common that I have a shortcut for this like

```
 template <typenameT, typename Tag>
  using ContainerType = strong::type<T,
                                  Tag,
                                  strong::range,
                                  strong::indexed<Index>,
                                  strong::default_constructible>;
```

being able to tell that ContainerType it should also forward the size(), not just begin and and, would be awesome.

**Comment by rollbear** [comment]
I don't expect that to be difficult. There are several other places where functionality is available depending on the support in the underlying type. I'll look into this in the next few days. Thank you for the suggestion.

**Comment by rollbear** [comment]
Just tagged v14 which includes this. Closing now.
