### ISSUE TITLE
error: binding reference of type 'XX' (aka 'char') to value of type 'XX' (aka 'const char') drops 'const' qualifier

### ISSUE THREAD

**Issue by mohabouje** [rollbear/strong_type#8]
The static cast should be to a reference underlying object and not to a const reference. 

https://github.com/rollbear/strong_type/blob/94315da12d0f85f297826b6393ec6ce87ebd9174/include/strong_type/strong_type.hpp#L1308

**Comment by rollbear** [comment]
Right! Will fix. Thank you!

**Comment by rollbear** [comment]
Are you in a hurry for a tag, or can I leave it as is, fixed on master?

**Comment by mohabouje** [comment]
No worries, I did fix it in a local fork.  I will upgrade it once a new version with the fix is released.
